<<<<<<< HEAD
baseURL = "http://kennesawmassage.services"
=======
baseURL = "https://kennesawmassage.services"
>>>>>>> 340d994672ba74b6b9e77e3eb4d9fd17e2b045c9
languageCode = "en-us"
title = "Wangs Body & Feet Massage"
theme = "ananke"

[menu]
   [[menu.main]]
    name="Services"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "services"
    url = "/services/"
   [[menu.main]]
    name = "Our Staff"
    pre = "<i class='fa fa-heart'></i>"
    weight = -100
    identifier = "our staff"
    url = "/ourstaff/"