baseURL = "http://updatetheme.d33fregj5h7efy.amplifyapp.com"
languageCode = "en-us"
title = "Wangs Body & Feet Massage"
theme = "ananke"

[menu]
   [[menu.main]]
    name="Services"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "services"
    url = "/services/"
   [[menu.main]]
    name = "Our Staff"
    pre = "<i class='fa fa-heart'></i>"
    weight = -100
    identifier = "our staff"
    url = "/ourstaff/"